[package]
name = "phog"
version = "0.1.3-alpha.0"
authors = ["Tomoki Aonuma <uasi@uasi.jp>"]
repository = "https://github.com/uasi/phog"
description = "phog downloads images from Twitter."
readme = "README.md"
license = "Apache-2.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
chrono = "0.4.15"
copypasta = { version = "0.7.0", default-features = false }
color-eyre = "0.5.1"
curl = "0.4.33"
dirs = "3.0.1"
egg-mode = "0.15.0"
hyper = "0.13.7"
indicatif = "0.15.0"
libc = "0.2.76"
linkify = "0.4.0"
log = "0.4.11"
once_cell = "1.4.1"
pretty_env_logger = "0.4.0"
regex = "1.3.9"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
signal-hook = "0.1.16"
smol = { version = "0.3.3", features = ["tokio02"] }
structopt = "0.3.16"
toml = "0.5.6"
url = "2.1.1"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.23.1", features = ["serde_json", "bundled"] }

[target.'cfg(not(windows))'.dependencies]
rusqlite = { version = "0.23.1", features = ["serde_json"] }

[dev-dependencies]
tempfile = "3.1.0"
